### PR TITLE
Fixed UI inputs caret position and focus

### PR DESCRIPTION
**Pull request by xGuTeK**
https://github.com/stevewgr/ko/issues/51

### CODE REVIEW

**Review by GiRx8 — APPROVED** [review]

**Comment by stevewgr** [comment]
@GiRx8 why merging? I did not approve the previous PR and you didn't even test the change, since it had error in syntax. I'll make workflows checks so that things can't be merged unless build is passing, as well as 2 reviewers unless it was me.

**Comment by GiRx8** [comment]
My bad!

**Comment by giladreich** [comment]
> My bad!

No worries. We'll fix that.

**Comment by ko4life-psko** [comment]
> My bad!

No worries, @GiRx8. We fixed `master` branch recent merged.

**Pull request merged**
