### PR TITLE
Update project to DirectX-9

### PR DESCRIPTION
**Pull request by stevewgr**
## Description

This PR upgrades the entire project to DirectX-9. note that Debug builds linking issue were fixed and explained in this commit: https://github.com/stevewgr/ko/pull/29/commits/f92e234aba40381a917856f6f3def0db8ea9a8d8

I wrote couple of nice regex patterns to speed up the process of updating with the addition of making sure that all instances were not missing. Regex pattern following replace tokens:
- `(\w*(D3D|DIRECT3D)\w+)8(\s+)`
  -  `$19$3`
- `([GS]et)TextureStageState(\s*\(.*,\s*)D3DTSS_(ADDRESSU|ADDRESSV|ADDRESSW|BORDERCOLOR|MAGFILTER|MINFILTER|MIPFILTER|MIPMAPLODBIAS|MAXMIPLEVEL|MAXANISOTROPY|SRGBTEXTURE|ELEMENTINDEX|DMAPOFFSET\s*,)`
  - `$1SamplerState$2D3DSAMP_$3`
- `([GS]et)VertexShader(\s*\()`
  - `$1FVF$2`
- `(SetStreamSource\s*\(.*,.*,)(.*\))`
  - `$1 0,$2`
- `(SetIndices\s*\(.*),.*(\s*\))`
  - `$1$2`
- `(CreateVertexBuffer\s*\(.*,[\r\n]*.*,[\r\n]*.*,[\r\n]*.*,[\r\n]*.*)\)`
  - `$1, NULL)`

Note that in order to use DirectX-9 with the old msvc6, the following workaround was implemented by defining with compiler check missing decorators: https://github.com/stevewgr/ko-vendor/commit/9da44bee9175df9f0a3285a8f21d1edbc4899db6

### CODE REVIEW

**Comment by stevewgr** [comment]
Rebased with master.

**Review by UTengine — APPROVED** [review]
Let's see

**Review by UTengine — APPROVED** [review]

**Review by GiRx8 — APPROVED** [review]

**Review by JanekCode — APPROVED** [review]
Well it should work :) 👍

**Comment by stevewgr** [comment]
@UTengine, @GiRx8 and @JanekCode, thanks a lot for the code review!

I rebased the PR and pipeline is passing: https://github.com/stevewgr/ko/runs/7366877404?check_suite_focus=true

Going to merged and deploy these changes to `master` now. 🚀

**Pull request merged**
