### PR TITLE
Update working directory, database default configs and docs.

### PR DESCRIPTION
**Pull request by stevewgr**
### Description

As we now fetch the ko-assets in a specific directory structure, for every project that depends on either the server or game assets, we set the working directory.

I also updated the defaults ini configurations for server database credentials, as well as updated the doucmentation.

### CODE REVIEW

**Comment by GiRx8** [comment]
Just a quick question, why are the map folders being split? (I know 1298 does it) but never understood the reasoning behind it.

**Review by GiRx8 — COMMENTED** [review]
Why are the odbc connections being changed?

**Comment by stevewgr** [comment]
> Just a quick question, why are the map folders being split? (I know 1298 does it) but never understood the reasoning behind it.

Great question! I'm not sure why at this point, since it's how it's setup with the official server files, even in 1298 version, but looks like the `*.evt` files are different. Maybe that explains.
I remember also trying once to use the same MAP dir and it caused other issues. I made a quick check with SMDs for example, looks like some are different and some same:
```
User@stevew /cygdrive/c/ko/ko/src/assets/server
$ sha256sum AIServer_MAP/battle_0516.smd
c1979b507feb711bbb10f3e44a6ab2fda697ae4034b7bff6859b87264317256c *AIServer_MAP/battle_0516.smd

User@stevew /cygdrive/c/ko/ko/src/assets/server
$ sha256sum Ebenezer_MAP/battle_0516.smd
c0cb23d1a5376361eaad9cc51c0f2da215bde3ffc33a850da6b9362634cedaeb *Ebenezer_MAP/battle_0516.smd

User@stevew /cygdrive/c/ko/ko/src/assets/server
$ sha256sum Ebenezer_MAP/free_0810.smd
704c9d68949414e23a370b69d169f5d89d8ab34c7b182e1ec8ea7177be722900 *Ebenezer_MAP/free_0810.smd

User@stevew /cygdrive/c/ko/ko/src/assets/server
$ sha256sum AIServer_MAP/free_0810.smd
704c9d68949414e23a370b69d169f5d89d8ab34c7b182e1ec8ea7177be722900 *AIServer_MAP/free_0810.smd
``` 
I think as next improvement cleaning up the current state of this project, is combining the two together, just to reduce resouces.

**Comment by GiRx8** [comment]
Alright!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by stevewgr** [comment]
> Why are the odbc connections being changed?

To keep this project's setup separate from existing configurations people already have. That way people don't have conflicts with their existing server setups. It will create less back and forth about common user errors where they ask us help, since it's separated from their existing setup.

**Comment by GiRx8** [comment]
> > Why are the odbc connections being changed?
> 
> To keep this project's setup separate from existing configurations people already have. That way people don't have conflicts with their existing server setups. It will create less back and forth about common user errors where they ask us help, since it's separated from their existing setup.

ok! sounds good

**Comment by stevewgr** [comment]
@GiRx8, I created a ticket about the MAP dir situation: https://github.com/stevewgr/ko/issues/76

**Pull request merged**
