### PR TITLE
Update project to msvc143 (aka Visual Studio 2022)

### PR DESCRIPTION
**Pull request by stevewgr**
## Decription

The following PR apart from doing some house keeping, it mainly upgrades the old compiler version to latest MSVC143(aka Visual Studio 2022).

Solution files for Game, Server and Tool were created as separated pieces.

Additionally some build optimizations were enabled to make the project build much faster than before thanks to precompiled headers.

### CODE REVIEW

**Review by GiRx8 — APPROVED** [review]
👍 would we still have to use the build.cmd as I see it’s still there?

**Comment by stevewgr** [comment]
> 👍 would we still be required to use the build.cmd as I see it’s still there?

The build.cmd is for convenient. Before it was useful since we had to set the old compiler explictly, now it's just for CI/CD.

**Comment by GiRx8** [comment]
> > 👍 would we still be required to use the build.cmd as I see it’s still there?
> 
> The build.cmd is for convenient. Before it was useful since we had to set the old compiler explictly, now it's just for CI/CD.

Alright.

**Review by UTengine — COMMENTED** [review]
Looks clean, will have to get used to it

**Review by UTengine — APPROVED** [review]
Looks clean, will have to get used to it

**Pull request merged**
